"""Keeps docs/setup.md's support table in step with the recipes.

``python -m nethackers.setup.docs`` rewrites the table between the markers in
place; tests/test_setup_recipes.py fails while it is stale. Dev-only: the docs
live in the repository, not the wheel.
"""
from __future__ import annotations

from pathlib import Path

from nethackers.setup import linux, macos
from nethackers.setup.support import render_table

START = ("<!-- setup-recipes:start (generated by `python -m nethackers.setup.docs`; "
         "do not edit by hand) -->")
END = "<!-- setup-recipes:end -->"
DOC = Path(__file__).resolve().parents[3] / "docs" / "setup.md"


def table() -> str:
    return render_table([("macOS", macos.RECIPES), ("Linux", linux.RECIPES)])


def with_table(text: str) -> str:
    """``text`` with the freshly generated table between the markers."""
    head, found, rest = text.partition(START)
    if not found:
        raise ValueError(f"{DOC} has no start marker")
    _old, found, tail = rest.partition(END)
    if not found:
        raise ValueError(f"{DOC} has no end marker")
    return f"{head}{START}\n\n{table()}\n{END}{tail}"


def main() -> int:
    DOC.write_text(with_table(DOC.read_text(encoding="utf-8")), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
