#!/usr/bin/env python3
"""Regenerate ``src/nethackers/_image_pins.py`` from freshly-published GHCR
image refs -- THE single source of the pins-file format.

``.github/workflows/sandbox-images.yml`` calls this right after it builds and
pushes the ``arena``/``mutator`` images, so the "re-pin ceremony"
(design spec section 8 / decision D11) is a generated, reviewable PR instead
of a hand-paste of two 64-hex digests. Stdlib only, so CI runs it with a bare
``python3`` (no ``uv``/deps) -- except that classifying the arena digest
(spec 2026-09-14 I7) reads ``nethackers.arena_version``, so the caller needs
``src`` on ``sys.path`` (``PYTHONPATH=src``, as the workflow sets) or an
installed ``nethackers``.

Usage (any subset; omitted values are kept from the current file). PYTHONPATH=src
because the arena guard below imports ``nethackers.arena_version``:
    PYTHONPATH=src python3 scripts/repin_images.py \\
        --arena          ghcr.io/dunnolab/nethackers-arena@sha256:<64 hex> \\
        --mutator        ghcr.io/dunnolab/nethackers-mutator@sha256:<64 hex> \\
        --nle-base       ghcr.io/dunnolab/nethackers-nle-base@sha256:<64 hex> \\
        --mutator-inputs sha256:<64 hex>
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# A digest-pinned OCI ref: <lowercase repo path>@sha256:<64 lowercase hex>. Only
# a DIGEST pin is acceptable here (never a mutable tag) -- that is the whole
# point of the pins file (content-addressed, reproducible).
_REF_RE = re.compile(r"^(?P<repo>[a-z0-9][a-z0-9._/-]*)@sha256:(?P<hex>[0-9a-f]{64})$")
_INPUTS_RE = re.compile(r"^sha256:[0-9a-f]{64}$")

_PINS = Path(__file__).resolve().parent.parent / "src" / "nethackers" / "_image_pins.py"

_DOCSTRING = (
    '"""GENERATED by scripts/repin_images.py -- do NOT hand-edit. The mutator pins are\n'
    "rewritten automatically by .github/workflows/mutator-image.yml, the arena and base\n"
    "pins by the manually dispatched .github/workflows/sandbox-images.yml. These are the\n"
    'digests this CLI version pulls (specs 2026-08-28 §5.4 and 2026-09-15 §5.2)."""'
)


def _assignment(name: str, ref: str) -> str:
    """One ``NAME = (\\n  "repo@sha256:"\\n  "<64 hex>"\\n)`` block -- split
    across lines because a full digest ref is well past the 100-col limit."""
    m = _REF_RE.match(ref.strip())
    if m is None:
        raise ValueError(
            f"{name}: expected a digest-pinned ref 'repo@sha256:<64 hex>', got {ref!r}")
    return (
        f"{name} = (\n"
        f'    "{m["repo"]}@sha256:"\n'
        f'    "{m["hex"]}"\n'
        ")\n"
    )


def render_pins(arena: str, mutator: str, nle_base: str, mutator_inputs: str) -> str:
    """The exact content ``_image_pins.py`` should have (deterministic +
    ruff-clean). Raises ``ValueError`` on a non-digest ref, a malformed
    fingerprint, or an arena digest that is not a key of
    ``ARENA_MAJOR_BY_DIGEST``.

    Note what that last check is and is NOT. It checks MEMBERSHIP in a
    hand-maintained map -- nothing here can look at a digest and tell whether
    it names a linux/amd64 manifest or a multi-arch index; that judgment was
    made by the human who added the entry. So it catches the expected
    regression (buildx reporting a fresh index digest, which nobody has
    classified) but would pass an already-classified index digest -- e.g.
    ``97ba883e…``, classified at major 1, is an index. The workflow's own
    guard step closes that gap for the current major by requiring
    ``major == ARENA_MAJOR``; a genuine amd64-vs-index assertion would need
    the registry, which this stdlib-only script deliberately does not touch.
    """
    if _INPUTS_RE.match(mutator_inputs) is None:
        raise ValueError(
            f"MUTATOR_INPUTS: expected 'sha256:<64 hex>', got {mutator_inputs!r}")

    # Spec 2026-09-14 I7: the arena pin names ONE platform's bytes, and that
    # digest must already be classified in arena_version.py. An index digest
    # (what buildx reports by default) is not classified, so emitting one would
    # silently revert the reference architecture and break registration for
    # everyone. Fail here instead. The import is function-local on purpose:
    # this module's header promises stdlib-only so CI can run it with a bare
    # interpreter, and this keeps that true for every path that does not reach
    # this guard (e.g. --help, or a malformed ref caught above).
    from nethackers.arena_version import ARENA_MAJOR_BY_DIGEST

    arena_digest = arena.strip().partition("@")[2]
    if arena_digest not in ARENA_MAJOR_BY_DIGEST:
        raise ValueError(
            f"arena: {arena_digest} is not a classified arena image. Pin the "
            f"linux/amd64 MANIFEST digest and add it to ARENA_MAJOR_BY_DIGEST "
            f"first (spec 2026-09-14 I7)."
        )

    arena_block = _assignment("ARENA_IMAGE", arena)

    return (
        f"{_DOCSTRING}\n"
        "from __future__ import annotations\n"
        "\n"
        f"{arena_block}"
        f"{_assignment('MUTATOR_IMAGE', mutator)}"
        f"{_assignment('NLE_BASE_IMAGE', nle_base)}"
        f'MUTATOR_INPUTS = "{mutator_inputs}"\n'
    )


def _current_pins(path: Path) -> dict[str, str]:
    """The string constants the existing pins file defines ({} when absent)."""
    if not path.exists():
        return {}
    ns: dict[str, object] = {}
    exec(compile(path.read_text(), str(path), "exec"), ns)  # noqa: S102 -- our generated file
    return {k: v for k, v in ns.items() if k.isupper() and isinstance(v, str)}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate _image_pins.py; omitted values are kept.")
    ap.add_argument("--arena", help="ghcr.io/…/nethackers-arena@sha256:<64 hex>")
    ap.add_argument("--mutator", help="ghcr.io/…/nethackers-mutator@sha256:<64 hex>")
    ap.add_argument("--nle-base", help="ghcr.io/…/nethackers-nle-base@sha256:<64 hex>")
    ap.add_argument("--mutator-inputs", help="sha256:<64 hex> (python -m nethackers.image_inputs)")
    ap.add_argument("--out", type=Path, default=_PINS,
                    help="target file (default: the real src/nethackers/_image_pins.py)")
    args = ap.parse_args(argv)
    current = _current_pins(args.out)
    given = {"ARENA_IMAGE": args.arena, "MUTATOR_IMAGE": args.mutator,
             "NLE_BASE_IMAGE": args.nle_base, "MUTATOR_INPUTS": args.mutator_inputs}
    pins = {name: value or current.get(name, "") for name, value in given.items()}
    missing = [name for name, value in pins.items() if not value]
    if missing:
        print(f"repin_images: no value for {', '.join(missing)} -- pass it, or keep it in --out",
              file=sys.stderr)
        return 2
    try:
        content = render_pins(pins["ARENA_IMAGE"], pins["MUTATOR_IMAGE"],
                              pins["NLE_BASE_IMAGE"], pins["MUTATOR_INPUTS"])
    except ValueError as exc:
        print(f"repin_images: {exc}", file=sys.stderr)
        return 2
    args.out.write_text(content)
    print(f"repin_images: wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
