#!/usr/bin/env python3
"""Regenerate ``src/nethackers/_image_pins.py`` from freshly-published GHCR
image refs -- THE single source of the pins-file format.

``.github/workflows/sandbox-images.yml`` calls this right after it builds and
pushes the multi-arch ``arena``/``mutator`` images, so the "re-pin ceremony"
(design spec section 8 / decision D11) is a generated, reviewable PR instead
of a hand-paste of two 64-hex digests. Stdlib only, so CI runs it with a bare
``python3`` (no ``uv``/deps).

Usage:
    python3 scripts/repin_images.py \\
        --arena   ghcr.io/dunnolab/nethackers-arena@sha256:<64 hex> \\
        --mutator ghcr.io/dunnolab/nethackers-mutator@sha256:<64 hex>
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# A digest-pinned OCI ref: <lowercase repo path>@sha256:<64 lowercase hex>. Only
# a manifest-list DIGEST pin is acceptable here (never a mutable tag) -- that is
# the whole point of the pins file (content-addressed, reproducible).
_REF_RE = re.compile(r"^(?P<repo>[a-z0-9][a-z0-9._/-]*)@sha256:(?P<hex>[0-9a-f]{64})$")

_PINS = Path(__file__).resolve().parent.parent / "src" / "nethackers" / "_image_pins.py"

_DOCSTRING = (
    '"""GENERATED by scripts/repin_images.py (run from '
    ".github/workflows/sandbox-images.yml\n"
    "after it builds+pushes the multi-arch sandbox images) -- the digests this "
    "CLI version\n"
    "pulls (spec §5.4). Do NOT hand-edit: trigger that workflow, which "
    "regenerates this\n"
    'file and opens the re-pin PR (spec section 8 / D11)."""'
)


def _assignment(name: str, ref: str) -> str:
    """One ``NAME = (\\n  "repo@sha256:"\\n  "<64 hex>"\\n)`` block -- split
    across lines because a full digest ref is well past the 100-col limit."""
    m = _REF_RE.match(ref.strip())
    if m is None:
        raise ValueError(
            f"{name}: expected a digest-pinned ref 'repo@sha256:<64 hex>', got {ref!r}")
    return (
        f"{name} = (\n"
        f'    "{m["repo"]}@sha256:"\n'
        f'    "{m["hex"]}"\n'
        ")\n"
    )


def render_pins(arena: str, mutator: str) -> str:
    """The exact content ``_image_pins.py`` should have for these two refs
    (deterministic + ruff-clean). Raises ``ValueError`` on a non-digest ref."""
    return (
        f"{_DOCSTRING}\n"
        "from __future__ import annotations\n"
        "\n"
        f"{_assignment('ARENA_IMAGE', arena)}"
        f"{_assignment('MUTATOR_IMAGE', mutator)}"
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate _image_pins.py from GHCR digest refs.")
    ap.add_argument("--arena", required=True, help="ghcr.io/…/nethackers-arena@sha256:<64 hex>")
    ap.add_argument("--mutator", required=True, help="ghcr.io/…/nethackers-mutator@sha256:<64 hex>")
    ap.add_argument("--out", type=Path, default=_PINS,
                    help="target file (default: the real src/nethackers/_image_pins.py)")
    args = ap.parse_args(argv)
    try:
        content = render_pins(args.arena, args.mutator)
    except ValueError as exc:
        print(f"repin_images: {exc}", file=sys.stderr)
        return 2
    args.out.write_text(content)
    print(f"repin_images: wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
