#!/usr/bin/env python3
"""Per-worktree stack isolation: allocate a deterministic host port + compose
project name for THIS worktree and persist them to a gitignored .env.stack,
reused verbatim thereafter. sha256(path) seed (NOT builtin hash(), which is
PYTHONHASHSEED-salted). Single-port trim of buro/scripts/worktree_stack.py."""
from __future__ import annotations

import hashlib
import re
import socket
import sys
from pathlib import Path

PORT_LO, PORT_SPAN = 28000, 1000
KEYS = ("NETHACKERS_STAGE", "NETHACKERS_HUB", "NETHACKERS_HUB_PORT",
        "COMPOSE_PROJECT_NAME", "NETHACKERS_DATA_ROOT", "NETHACKERS_REPO_NAME",
        "NETHACKERS_ARENA_IMAGE")


def slug(worktree: Path) -> str:
    return re.sub(r"[^a-z0-9]+", "-", worktree.resolve().name.lower()).strip("-")


def seed_port(worktree: Path) -> int:
    digest = hashlib.sha256(str(worktree.resolve()).encode()).digest()
    return PORT_LO + int.from_bytes(digest[:4], "big") % PORT_SPAN


def port_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def _pick_port(worktree: Path, is_free) -> int:
    start = seed_port(worktree)
    for off in range(PORT_SPAN):
        port = PORT_LO + (start - PORT_LO + off) % PORT_SPAN
        if is_free(port):
            return port
    raise RuntimeError("no free port in range")


def render(vars: dict[str, str]) -> str:
    body = "\n".join(f"{k}={vars[k]}" for k in vars)
    return ("# generated by scripts/stack.py -- this worktree's stage; "
            "gitignored, reused verbatim by `make up`\n" + body + "\n")


def parse(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip()
    return out


def allocate(worktree: Path, is_free=port_free) -> dict[str, str]:
    env_stack = worktree / ".env.stack"
    if env_stack.exists():                       # reuse verbatim: the file is the record
        return parse(env_stack.read_text())
    s = slug(worktree)
    port = _pick_port(worktree, is_free)
    vars = {
        "NETHACKERS_STAGE": s,
        "NETHACKERS_HUB": f"http://localhost:{port}",   # derived from the port -> no drift
        "NETHACKERS_HUB_PORT": str(port),
        "COMPOSE_PROJECT_NAME": f"nethackers-{s}",
        "NETHACKERS_DATA_ROOT": str(worktree.resolve() / ".nethackers"),
        "NETHACKERS_REPO_NAME": f"nh-dev-{s}",
        "NETHACKERS_ARENA_IMAGE": f"nethackers/arena:{s}",
    }
    env_stack.write_text(render(vars))
    return vars


if __name__ == "__main__":
    v = allocate(Path.cwd())
    for k in KEYS:
        print(f"{k}={v[k]}")
    print(f"stage {v['NETHACKERS_STAGE']} -> hub {v['NETHACKERS_HUB']}", file=sys.stderr)
