"""GENERATED by scripts/repin_images.py -- do NOT hand-edit. The mutator pins are
rewritten automatically by .github/workflows/mutator-image.yml, the arena and base
pins by the manually dispatched .github/workflows/sandbox-images.yml. These are the
digests this CLI version pulls (specs 2026-08-28 §5.4 and 2026-09-15 §5.2)."""
from __future__ import annotations

ARENA_IMAGE = (
    "ghcr.io/dunnolab/nethackers-arena@sha256:"
    "97ba883e04fd79d334c9074bfd92bfe8b0c923a0882881bef5435b369b6a1601"
)
MUTATOR_IMAGE = (
    "ghcr.io/dunnolab/nethackers-mutator@sha256:"
    "95a62b174c599cef07385c1067988220906d275193bc30a4d8c7b90976376108"
)
NLE_BASE_IMAGE = (
    "ghcr.io/dunnolab/nethackers-nle-base@sha256:"
    "d03eadf7c4cede31ffe317dc6ea9c230e488a319cd1e561ab7b61d7988c55a8d"
)
MUTATOR_INPUTS = "sha256:8156cfd8f82c9fc6b6c0488e34e81fbbbb8d57f4935eafa18ae4aee6b8073d3a"
