"""GENERATED by scripts/repin_images.py (run from .github/workflows/sandbox-images.yml
after it builds+pushes the multi-arch sandbox images) -- the digests this CLI version
pulls (spec §5.4). Do NOT hand-edit: trigger that workflow, which regenerates this
file and opens the re-pin PR (spec section 8 / D11)."""
from __future__ import annotations

ARENA_IMAGE = (
    "ghcr.io/dunnolab/nethackers-arena@sha256:"
    "d18bff83ace72a35cbbfde29df8e2da73f6a4a7c2e48bbb0ac488ac9c45c12e3"
)
MUTATOR_IMAGE = (
    "ghcr.io/dunnolab/nethackers-mutator@sha256:"
    "ae467d9d645690a0d843452798e1a642e49a0d05f3b33708dd82c965872c114e"
)
