"""GENERATED by scripts/repin_images.py (run from .github/workflows/sandbox-images.yml
after it builds+pushes the multi-arch sandbox images) -- the digests this CLI version
pulls (spec §5.4). Do NOT hand-edit: trigger that workflow, which regenerates this
file and opens the re-pin PR (spec section 8 / D11)."""
from __future__ import annotations

ARENA_IMAGE = (
    "ghcr.io/dunnolab/nethackers-arena@sha256:"
    "9b63a7b1fb11a82c01797a1099774b4e0ef6e321fbacd3a2256d8db6b4428142"
)
MUTATOR_IMAGE = (
    "ghcr.io/dunnolab/nethackers-mutator@sha256:"
    "003b998d740a274778c3132da4dafe32e5fd7d88a7b523611d1d7ce8185f1b72"
)
